name: 🚀 Deploy website on push
on: 
  push:
    branches:
      -main
jobs:
  web-deploy:
    name: FTP-Deploy_Action
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
